/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.TaiSanJFrame;

import Bean.TaiSanBean;
import controllers.TaiSanController.DeleteTaiSanController;
import controllers.TaiSanPanelController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.security.interfaces.RSAKey;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import services.MysqlConnection;

/**
 *
 * @author Thanh.ND200592
 */
public class DeleteTaiSanFrame extends javax.swing.JFrame {

    /**
     * Creates new form DeleteTaiSanFrame
     */
    private TaiSanPanelController parentController;
    private JFrame parentFrame;
    private TaiSanBean taiSanBean;
    private DeleteTaiSanController controller;
    public DeleteTaiSanFrame( TaiSanPanelController parentController, JFrame parentJFrame) {
        this.parentController = parentController;
        this.parentFrame = parentJFrame;
        this.parentFrame.setEnabled(false);
        initComponents();
        setTitle("Xóa tài sản");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        controller = new DeleteTaiSanController();
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing (WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn đóng??", "Warning!", JOptionPane.YES_NO_OPTION)==0) {
                    close();
                }
            }
        });
    }
    
    public DeleteTaiSanFrame(JFrame parentJFrame) {
        this.parentController = new TaiSanPanelController(){
            @Override
            public void refreshData() {
                
            }
            @Override
            public void initAction() {
                
            }
        };
        this.parentFrame = parentJFrame;
        this.parentFrame.setEnabled(false);
        initComponents();
        setTitle("Xóa tài sản");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        controller = new DeleteTaiSanController();
        
                this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn thoát??", "Warning!!", JOptionPane.YES_NO_OPTION)==0) {
                    close();
                }
            }
        });
         }
     void close() {
         this.parentFrame.setEnabled(true);
         dispose();
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlbName = new javax.swing.JLabel();
        jlbCount = new javax.swing.JLabel();
        jlbCurrent = new javax.swing.JLabel();
        txbID = new javax.swing.JTextField();
        btnCheck = new javax.swing.JButton();
        txbName = new javax.swing.JTextField();
        txbCount = new javax.swing.JTextField();
        txbCurrent = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("XÓA TÀI SẢN");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("ID");

        jlbName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlbName.setText("Tên tài sản");

        jlbCount.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlbCount.setText("Số lượng");

        jlbCurrent.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlbCurrent.setText("Số lượng hiện có");

        txbID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        btnCheck.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        txbName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        txbCount.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        txbCurrent.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        btnDelete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jlbCount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txbID))
                                .addGap(32, 32, 32)
                                .addComponent(btnCheck))
                            .addComponent(txbName)
                            .addComponent(txbCount)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txbCurrent)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txbID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheck))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbName)
                    .addComponent(txbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCount)
                    .addComponent(txbCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCurrent)
                    .addComponent(txbCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnDelete)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed

        try {
            Connection connection = MysqlConnection.getMysqlConnection();
            String query = "SELECT * FROM tai_san WHERE ID = '" + txbID.getText() + "'";
            PreparedStatement preparedStatement = connection.prepareStatement(query);
            ResultSet rs = preparedStatement.executeQuery();
            if (rs.next()) {
                txbName.setText(rs.getString("TenTaiSan"));
                txbCount.setText(rs.getInt("SoLuong") + "");
                txbCurrent.setText(rs.getInt("SoLuongConLai") + "");

            } else {
                JOptionPane.showMessageDialog(this, "ID không tồn tại\n Hãy kiểm tra l");
            }

        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (validateValueForm()) {
            
        try {
            if (this.controller.deleteTaisan(Integer.parseInt(txbID.getText()))) {
                JOptionPane.showMessageDialog(null, "Đã xóa thành công");
                close();
                parentController.refreshData();
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Có lỗi xảy ra. Vui lòng kiểm tra lại", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

      private boolean validateValueForm() {
        if (txbName.getText().trim().isEmpty()
                || txbCount.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Hãy nhập đủ các trường bắt buộc!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbCount;
    private javax.swing.JLabel jlbCurrent;
    private javax.swing.JLabel jlbName;
    private javax.swing.JTextField txbCount;
    private javax.swing.JTextField txbCurrent;
    private javax.swing.JTextField txbID;
    private javax.swing.JTextField txbName;
    // End of variables declaration//GEN-END:variables
}
